name: Weather Data Collection

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  collect-weather-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openmeteo-requests
        pip install polars
        pip install requests-cache
        pip install retry-requests
        
    - name: Run weather data collection
      run: python weather_fetcher.py
      
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add weather_data/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update weather data [skip ci]" && git push)